apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-spring-boot-service
  namespace: test-namespace
spec:
  selector:
    matchLabels:
      app: test-spring-boot-service
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: test-spring-boot-service
    spec:
      containers:
        - name: test-spring-boot-service
          image: test-spring-boot-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 8090