apiVersion: v1
kind: Service
metadata:
  name: test-spring-boot-service
spec:
  selector:
    app: test-spring-boot-service
  ports:
    - name: "public"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
    - name: "actuator"
      protocol: "TCP"
      port: 8090
      targetPort: 8090
  type: LoadBalancer
