management:
  endpoints.web.exposure.include: '*'

server:
  port: 8080
  ssl.enabled: false

logging:
  level:
    test: debug
    root: info

spring:
  kafka:
    streams:
      bootstrap-servers: "localhost:9092"